version: '3.8'

services:
  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: eaglegpt_pipelines
    restart: unless-stopped
    ports:
      - "9099:9099"
    environment:
      # Set the API key that OpenWebUI will use to connect
      PIPELINES_API_KEY: "sk-eaglegpt-pipeline-key"
      
      # Rate limiting defaults (can be overridden in UI)
      RATE_LIMIT_PER_MINUTE: "10"
      RATE_LIMIT_PER_HOUR: "50"
      RATE_LIMIT_SLIDING_WINDOW: "100"
      RATE_LIMIT_SLIDING_WINDOW_MINUTES: "180"
    volumes:
      # Mount local pipelines directory
      - ./pipelines:/app/pipelines
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - eaglegpt-network

networks:
  eaglegpt-network:
    external: true